#with databaseName = destSession.getPhysicalDatabaseName()
ALTER DATABASE [${databaseName}] SET ANSI_NULL_DEFAULT OFF 
ALTER DATABASE [${databaseName}] SET ANSI_NULLS OFF 
ALTER DATABASE [${databaseName}] SET ANSI_PADDING OFF 
ALTER DATABASE [${databaseName}] SET ANSI_WARNINGS OFF 
ALTER DATABASE [${databaseName}] SET ARITHABORT OFF 
ALTER DATABASE [${databaseName}] SET AUTO_CLOSE OFF 
ALTER DATABASE [${databaseName}] SET AUTO_CREATE_STATISTICS OFF 
ALTER DATABASE [${databaseName}] SET AUTO_SHRINK OFF 
ALTER DATABASE [${databaseName}] SET AUTO_UPDATE_STATISTICS OFF 
ALTER DATABASE [${databaseName}] SET CURSOR_CLOSE_ON_COMMIT OFF 
ALTER DATABASE [${databaseName}] SET CURSOR_DEFAULT  GLOBAL 
ALTER DATABASE [${databaseName}] SET CONCAT_NULL_YIELDS_NULL OFF 
ALTER DATABASE [${databaseName}] SET NUMERIC_ROUNDABORT OFF 
ALTER DATABASE [${databaseName}] SET QUOTED_IDENTIFIER OFF 
ALTER DATABASE [${databaseName}] SET RECURSIVE_TRIGGERS OFF 
ALTER DATABASE [${databaseName}] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
ALTER DATABASE [${databaseName}] SET DATE_CORRELATION_OPTIMIZATION OFF 
ALTER DATABASE [${databaseName}] SET PARAMETERIZATION SIMPLE 
ALTER DATABASE [${databaseName}] SET READ_WRITE 
ALTER DATABASE [${databaseName}] SET RECOVERY SIMPLE
ALTER DATABASE [${databaseName}] SET PAGE_VERIFY CHECKSUM
ALTER DATABASE [${databaseName}] SET SINGLE_USER
ALTER DATABASE [${databaseName}] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
GO
#end