#with databaseName = destSession.getPhysicalDatabaseName()
ALTER DATABASE [${databaseName}] SET AUTO_CREATE_STATISTICS ON 
ALTER DATABASE [${databaseName}] SET AUTO_UPDATE_STATISTICS ON 
ALTER DATABASE [${databaseName}] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
ALTER DATABASE [${databaseName}] SET DATE_CORRELATION_OPTIMIZATION ON 
ALTER DATABASE [${databaseName}] SET RECOVERY FULL
ALTER DATABASE [${databaseName}] SET PAGE_VERIFY TORN_PAGE_DETECTION
#end